### ISSUE TITLE
Difference between the types of balancers

### ISSUE THREAD

**Issue by devedse** [raynquist/balancer#1]
Hello raynquist, I got a question, there's a lot of different types of balancers and I don't quite understand the difference:
![image](https://user-images.githubusercontent.com/2350015/118343484-a6b37f00-b529-11eb-8f3c-be5b3246ecf2.png)

I also read some things about MadZuri balancers. Do you have any idea what those are?

**Comment by raynquist** [comment]
T or tu: throughput unlimited
L: lane balancer
red_blue: only works with red or blue belts
blue: only works with blue belts

That's about all the important ones.  The UG and the I are there just to differentiate it from other versions of the same balancer.

MadZuri did create some regular balancers, but you're probably referring to the circuit one.  He uses circuits to disable inserters as needed to prevent any buffer chests from draining/filling more than the others.

**Comment by raynquist** [comment]
I've added short descriptions of lane balancers and throughput unlimited balancers to relevant blueprints.
